### ISSUE TITLE
Practica 3_Operaciones con sistemas numericos_A1S_ Ortiz Reyes Jose Luis 

### ISSUE THREAD

**Issue by chelui5** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-chelui5#1]
[Actividad.3_Jose Luis Ortiz Reyes_A1S_Matematicas.Discretas..pdf](https://github.com/user-attachments/files/16847214/Actividad.3_Jose.Luis.Ortiz.Reyes_A1S_Matematicas.Discretas.pdf)

**Comment by Johnc-byte** [comment]
portada: 25
Procedimiento:17
Figuras, ilustraciones, fotografías: 25
Resultados y conclusiones: 24
Calificación de la práctica: 18
